### ISSUE TITLE
No BT module - "Installed version undefined.undefined.undefined"

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/Addon-Bluetooth-WebGUI#2]
First issue here :-).
No hurry, but a small improvement:

if there is no BLE module installed, it would be better to see something like "not available" instead
of "undefined.undefined.undefined".

**Comment by klues** [comment]
Hmm, where do you mean? For me it looks like this with no BT module installed: https://i.imgur.com/62WGz39.png
We could change "unknown" to "not installed", maybe that would be clearer.

**Comment by benjaminaigner** [comment]
You are right, normally this is shown (sorry, I forgot to update this issue when I found the "right" message).
But on some occasions, I got the mentioned message.
(bulk flashing ESP32 updates with the same browser window, but hitting refresh to re-connect).

**Comment by klues** [comment]
Improved upgrade process with https://github.com/asterics/Addon-Bluetooth-WebGUI/issues/3 so hopefully this error shouldn't occur anymore.
