### ISSUE TITLE
"Upload & replace all slots" -> slots are renamed unintentionally

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/Addon-Bluetooth-WebGUI#7]
Dear @klues 
when I use the upload and replace all slots functionality to reset the FABI to a known state. following problem occurs:

If there is an existing slot with the name from the selected file, the slot name is changed by adding a trailing "(1)".
The old slot is deleted though, so there is only one slot as intended, but with a different name.

Reproduce:
download all your current slots and upload the same file. If you do that once, slots are with a different name, if you do it twice, original names are restored.

**Comment by ChrisVeigl** [comment]
a sideeffect of this renaming procedure is that the maximum slotname size could be exceeded, which results in a different slotname in webGUI and device so the this slot cannot be selected anymore.

I would suggest to have the "replace all slots" functionality as default. IMO, adding single slots is a special case which should be hidden by default (maybe a button "add/select individual slots" which then displays the slotnames + checkboxes). 
 
In case of existing slot name, I'd suggest to delete the existing slot, thereby getting rid of the rename problem.

**Comment by benjaminaigner** [comment]
>a sideeffect of this renaming procedure is that the maximum slotname size could be exceeded, which results in a different slotname in webGUI and device so the this slot cannot be selected anymore. 

I had that case, the last ")" was missing on the device.

> I would suggest to have the "replace all slots" functionality as default. IMO, adding single slots is a special case which should be hidden by default (maybe a button "add/select individual slots" which then displays the slotnames + checkboxes).

I find this functionality very useful, but it could be possible to "hide" it behind an advanced button (or something similar).

> In case of existing slot name, I'd suggest to delete the existing slot, thereby getting rid of the rename problem.

Maybe we could ask "overwrite" or "rename"? Like in the file managers...

**Comment by klues** [comment]
Thanks for reporting! Renaming slots on "upload an replace all" is indeed a bug and also the issue with bypassing the maximum slot length by renaming has to be fixed.

I would do the following:
By default only show "upload and replace all slots" and additionally a link to show advanced options where single slots can be selected. Would look like this: https://i.imgur.com/QkdoJIx.png
In the advanced options there could also be a checkbox "overwrite existing" to define if existing names should be overwritten or renamed.
What do you think?

**Comment by ChrisVeigl** [comment]
looks great !

**Comment by klues** [comment]
cool: if you add `fixes <link-to-issue>` in a git commit comment, it automatically closes the issue on github :)
